timezone: Pacific/Auckland

paths:
  static: public
  uploads: public/assets/uploads

commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'

collections_config:
  pages:
    path: src/pages
    glob:
      - '**/*.astro'
    url: '/[full_slug]/'
    icon: laptop_mac
    disable_url: false
    disable_add_folder: true
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: source_page
        icon: pages
    schemas:
      source_page:
        name: Source Editable Page
        path: '.cloudcannon/schemas/source-page.astro'
        remove_extra_inputs: false
        hide_extra_inputs: true
    create:
      path: '[relative_base_path]/{filename|slugify|lowercase}.astro'
    new_preview_url: /

collection_groups:
  - heading: Pages
    collections:
      - pages

_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: false
    horizontalrule: true
    image: false
    table: false
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    image_size_attributes: false
